name: Deploy DocC to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build DocC documentation (iOS Simulator)
        run: |
          set -euxo pipefail
          xcodebuild -list || true
          xcodebuild docbuild \
            -scheme ImageDownloader \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath .docc-build \
            | xcpretty || true
          DOCC=$(xcrun --find docc)
          "$DOCC" process-archive \
            transform-for-static-hosting .docc-build/Build/Products/Debug-iphonesimulator/ImageDownloader.doccarchive \
            --output-path docs \
            --hosting-base-path Image-Downloader

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --cached --quiet && echo "No documentation changes to commit." || git commit -m "Update DocC documentation"
          git push
